# <font color="#084B8A"> Taller de herramientas computacionales </font>
## Python - Notas de clase  
***Facultad de Ciencias, UNAM***  
*Semestre 2024-2*  
Jorge Zavaleta Sánchez

# Arreglos

Para manejar colecciones de datos, esto se puede hacer en Python mediante diferentes estructuras de datos:

* **Listas** (`list`). Puede cambiar de forma dinámica su contenido mediante sus métodos, además de que puede contener diferentes tipos de datos.
* **Tuplas** (`tuple`). Es equivalente a una lista, pero con la diferencia de que no puede cambiar de tamaño ni su contenido.

**Notas**:

* Tanto las listas como las tuplas son el análogo a un *arreglo*, pero con la diferencia de que pueden tener diferentes tipos de datos.
* La numeración de los indices comienza en 0 (cero).
* El acceso a los elementos se hace a través de corchetes `[]`.
* Se pueden generar arreglos n-dimensionales.

## Listas

Se generan mediante corchetes `[]` y los elementos se separan mediante comas (`,`). Para generar listas n-dimensionales es necesario anidar listas, es decir, hacer listas de listas.

In [3]:
# Lista simple con el mismo tipo de dato
L = [1, 2, 3, 4, 5, 6]
type(L)

list

In [4]:
# Lista simple con diferentes tipos de dato
L2 = [1, 'Algo', True]
print(L2)

[1, 'Algo', True]


In [5]:
# Acceso al segundo elemento de la lista
L2[1]

'Algo'

In [6]:
# Lista bidimensional, analogo a poner directamente [[1,'Algo',True],[1,2,3,4,5,6]]
L3 = [L2, L]
print(L3)

[[1, 'Algo', True], [1, 2, 3, 4, 5, 6]]


In [7]:
# Acceso al segundo elemento de la primera lista
L3[0][1]

'Algo'

In [8]:
# Lista tridimensional
L4 = [L3, L3]
print(L4)

[[[1, 'Algo', True], [1, 2, 3, 4, 5, 6]], [[1, 'Algo', True], [1, 2, 3, 4, 5, 6]]]


In [9]:
# Acceso al cuarto elemento de la segunda lista de la primera lista
L4[0][1][3]

4

Las listas son elementos **mutables**, es decir, una vez creados se puede cambiar su contenido. Una de las formas de hacerlo es a través de la referencia de sus índices.

In [10]:
print('L2 =', L2)
L2[1] = 4.5
print('L2 =', L2)

L2 = [1, 'Algo', True]
L2 = [1, 4.5, True]


Hay que tener cierto cuidado cuando se crea una "copia" de una lista con el operador de asignación `=`. Esto es debido a que no se genera una copia, si no se crea otra variable que apunta a la misma dirección de memoria donde se encuentra la lista de origen. De esta manera, los cambios en un lista implican cambios en ambas listas.

In [11]:
# Se crea la variable LL que apunta a L2
LL = L2
print('LL =', LL, '\n')

# Se hace un cambio en LL
LL[2] = -3.4
print('LL =', LL)
print('L2 =', L2, '\n')

# Se hace un cambio en L2
L2[0] = 'Cambio'
print('LL =', LL)
print('L2 =', L2)

LL = [1, 4.5, True] 

LL = [1, 4.5, -3.4]
L2 = [1, 4.5, -3.4] 

LL = ['Cambio', 4.5, -3.4]
L2 = ['Cambio', 4.5, -3.4]


Se puede modificar el tamaño de la lista a través de los métodos definidos para listas. Recuérdese que Python es un lenguaje de programación orientado a objetos, en el cual cada tipo de dato es un *objeto* definido mediante sus *atributos*, que es lo que define el estado de cada objeto, y este objeto cuenta con diferentes *métodos*, los cuales pueden ser pensados como funciones que actúan sobre los atributos.

Para acceder a los métodos es necesario poner `.` después del objeto y escribir el nombre del método, que incluso puede tener argumentos adicionales. En Colab/Jupyter y en algunas interfaces de desarrollo (IDEs) es posible mostrar los métodos disponibles para un objeto usando la tecla del **tabulador**. Para ello después de poner `.` apretamos la tecla *Tab* y aparecerá un menú, como se muestra en la siguiente imagen

![liga](https://i.stack.imgur.com/uOoZ5.png)

*En general no se hará énfasis en la parte orientada a objetos pero se usarán los métodos cuando sea conveniente*.

### Métodos para lista

Se muestran mediante ejemplos el uso de los métodos para listas.

* El método `append(elem)` permite agregar el nuevo elemento `elem` al final de la lista:

In [12]:
# Agregando el numero 7 al final de la lista L con el metodo append
print('L =', L)
L.append(7)
print('L =', L)

L = [1, 2, 3, 4, 5, 6]
L = [1, 2, 3, 4, 5, 6, 7]


* El método `insert(i, elem)` permite agregar el nuevo elemento `elem` en la posición indicada por el índice `i`:

In [13]:
# Agregando la cadena 'Hola' en la posicion (indice) 3 de la lista L con el metodo insert
print('L =', L)
L.insert(3, 'Hola')
print('L =', L)

L = [1, 2, 3, 4, 5, 6, 7]
L = [1, 2, 3, 'Hola', 4, 5, 6, 7]


* El método `copy()` permite crear una copia de la lista:

In [14]:
# Se crea una copia mediante el metodo copy
print('L =', L)
LC = L.copy()
print('LC =', LC)

L = [1, 2, 3, 'Hola', 4, 5, 6, 7]
LC = [1, 2, 3, 'Hola', 4, 5, 6, 7]


* El método `count(x)` cuenta el número de veces que aparece `x` en la lista:

In [15]:
# Contando las apariciones de 1, 'Hola', -7.5 en LC con el metodo count
LC.append(1)
print('LC =', LC)
print(f'{1} aparece {LC.count(1)} veces en {LC}')
print(f'{"Hola"} aparece {LC.count("Hola")} veces en {LC}')
print(f'{-7.5} aparece {LC.count(-7.5)} veces en {LC}')

LC = [1, 2, 3, 'Hola', 4, 5, 6, 7, 1]
1 aparece 2 veces en [1, 2, 3, 'Hola', 4, 5, 6, 7, 1]
Hola aparece 1 veces en [1, 2, 3, 'Hola', 4, 5, 6, 7, 1]
-7.5 aparece 0 veces en [1, 2, 3, 'Hola', 4, 5, 6, 7, 1]


* El método `extend(list)` agrega todos los elementos de la lista `list` a la lista:

In [16]:
# Agregando el contenido de L en LC con el metodo extend
print('LC =', LC)
LC.extend(L)
print('LC =', LC)

LC = [1, 2, 3, 'Hola', 4, 5, 6, 7, 1]
LC = [1, 2, 3, 'Hola', 4, 5, 6, 7, 1, 1, 2, 3, 'Hola', 4, 5, 6, 7]


* El método `index(x)` determina el primer índice donde aparece `x`. Si no se encuentra en la lista manda un error de tipo `ValueError`:

In [19]:
# Buscando el indice de LC donde se encuentra 'Hola' con el metodo index
print(f'{"Hola"} está en el índice {LC.index("Hola")}')

# La siguiente linea de codigo mandaria un ValueError
#print(f'{10} está en el índice {LC.index(10)}')

Hola está en el índice 3


* El método `pop(i)` elimina el elemento en el índice `i`. Si no se da, se elimina el último elemento de la lista:

In [20]:
# Eliminando algunos elementos de LC con el metodo pop
print('LC =', LC)
LC.pop() #  El ultimo elemento
print('LC =', LC)
LC.pop(3) #  El elemento en el indice 3
print('LC =', LC)

LC = [1, 2, 3, 'Hola', 4, 5, 6, 7, 1, 1, 2, 3, 'Hola', 4, 5, 6, 7]
LC = [1, 2, 3, 'Hola', 4, 5, 6, 7, 1, 1, 2, 3, 'Hola', 4, 5, 6]
LC = [1, 2, 3, 4, 5, 6, 7, 1, 1, 2, 3, 'Hola', 4, 5, 6]


* El método `reverse()` invierte el orden de los elementos de la lista:

In [21]:
# Cambiando el orden de los elementos en LC con el metodo reverse
print('LC =', LC)
LC.reverse()
print('LC =', LC)

LC = [1, 2, 3, 4, 5, 6, 7, 1, 1, 2, 3, 'Hola', 4, 5, 6]
LC = [6, 5, 4, 'Hola', 3, 2, 1, 1, 7, 6, 5, 4, 3, 2, 1]


* El método `remove(x)` elimina la primera aparición de `x` de la lista. Si no se encuentra en la lista manda un error de tipo `ValueError`:

In [22]:
# Eliminando de LC la primera aparicion de 'Hola' y 6 de la lista con el metodo remove
print('LC =', LC)
LC.remove('Hola')
print('LC =', LC)
LC.remove(6)
print('LC =', LC)

# La siguiente linea de codigo mandaria un ValueError
#LC.remove(-6)

LC = [6, 5, 4, 'Hola', 3, 2, 1, 1, 7, 6, 5, 4, 3, 2, 1]
LC = [6, 5, 4, 3, 2, 1, 1, 7, 6, 5, 4, 3, 2, 1]
LC = [5, 4, 3, 2, 1, 1, 7, 6, 5, 4, 3, 2, 1]


* El método `sort()` ordena los elementos dentro de la lista de manera ascendente. Para usarse, los tipos de datos dentro de la lista deben soportar el uso del operador `<`, sino mandará un error de tipo `TypeError`

In [23]:
# Ordenando la lista de manera ascendente con el metodo sort
print('LC =', LC)
LC.sort()
print('LC =', LC)

LC = [5, 4, 3, 2, 1, 1, 7, 6, 5, 4, 3, 2, 1]
LC = [1, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 7]


* El método `clear()` elimina todos los elementos de la lista. Después de aplicar este método, la lista queda vacía:

In [24]:
# Vaciando la lista con el metodo clear
print('LC = ', LC)
LC.clear()
print('LC = ', LC)

LC =  [1, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 7]
LC =  []


También es posible ocupar algunos operadores sobre listas. El operador `+` sirve para concatenar dos listas (de forma análoga a `expand`) en una nueva. El operador `*` se usa un conjunto con un entero `n` para replicar el contenido de la lista tantas veces como lo indíque `n`.

In [25]:
# Concatenando LC con L y lo reescribimos en LC
LC = LC + L
print('LC =', LC)

# Duplicando el contenido de la lista
LC = 2*LC
print('LC =', LC)

LC = [1, 2, 3, 'Hola', 4, 5, 6, 7]
LC = [1, 2, 3, 'Hola', 4, 5, 6, 7, 1, 2, 3, 'Hola', 4, 5, 6, 7]


## Tuplas

Se generan mediante paréntesis `()` y los elementos se separan mediante comas `,
`. Para generar tuplas n-dimensionales es necesario anidar tuplas, es decir, hacer tuplas de tuplas.

In [26]:
# Tupla
T = (1, 2, 3, 4)
type(T)

tuple

In [27]:
# Acceso al segundo elemento en la tupla T
T[1]

2

In [28]:
# Tupla bidimensional y acceso mediante 2 indices
T2 = (T, T)
print(T2)
T2[0][0]

((1, 2, 3, 4), (1, 2, 3, 4))


1

In [29]:
# Se puede combinar tuplas con listas y viceversa
T3 = (T, L)
print(T3)

((1, 2, 3, 4), [1, 2, 3, 'Hola', 4, 5, 6, 7])


In [30]:
# Mostrando el tipo al que corresponde
print(type(T3))  # Tupla
print(type(T3[0]))  # Tupla
print(type(T3[1]))  # Lista
T3[1][3]  # Acceso usual mientras el objeto lo permita

<class 'tuple'>
<class 'tuple'>
<class 'list'>


'Hola'

A diferencia de las listas, las tuplas son elementos no mutables y por tanto no podemos modificar su contenido ni tamaño. Así, los únicos métodos disponibles para las tuplas son `count` e `index`.

In [31]:
# Contando las veces que aparece 1 en T con el metodo count
T.count(1)

1

In [32]:
# Encontrando el primer indice de T donde aparece 3 con el metodo index
T.index(3)

2

## Acceso a porciones de un arreglo (*slices*)

Es posible acceder de forma dinámica a los elementos de un arreglo mediante `:`.

**Nota**: El acceso está dado de la siguiente manera: `inicio : final : incremento`, que se conocen como *slices*. Una cosa importante que se debe considerar en este caso es que el valor final no se toma en cuenta, es decir, los valores son tomados menores estrictos que el valor final. Por ejemplo, si lo consideramos como un intervalo, los valores están en $[inicio,final)$.

In [34]:
# Todos los elementos de la lista
L[:]

[1, 2, 3, 'Hola', 4, 5, 6, 7]

In [33]:
# Los valores de L del indice 3 hasta el 5 (6 menos el incremento de 1 que esta implicito)
L[3:6]

['Hola', 4, 5]

In [35]:
# Del indice 3 hasta el final de la lista
L[3:]

['Hola', 4, 5, 6, 7]

In [36]:
# Del inicio de la lista hasta el indice 2 (3 menos el incremento de 1 que esta implicito)
L[:3]

[1, 2, 3]

In [37]:
# Del indice 2 hasta el indice 5 con incrementos de 2
L[1:6:2]

[2, 'Hola', 5]

**Nota**: Si se usan valores negativos, el arreglo se recorre del final al inicio, donde el último elemento tendría el índice `-1`.

In [38]:
# Ultimo elemento de L
L[-1]

7

In [39]:
# Recorriendo de atras hacia adelante la lista
L[::-1]

[7, 6, 5, 4, 'Hola', 3, 2, 1]

La función `len` permite determinar la longitud de una cadena, lista, tupla, etc.

In [40]:
# Calculamos el numero de elementos dentro de un arreglo
print(f"La longitud de la cadena 'Cadena' es {len('Cadena')}")  # Cadena
print(f"La longitud de la lista {L} es {len(L)}")  # Lista
print(f"La longitud de la tupla {T} es {len(T)}")  # Tupla

La longitud de la cadena 'Cadena' es 6
La longitud de la lista [1, 2, 3, 'Hola', 4, 5, 6, 7] es 8
La longitud de la tupla (1, 2, 3, 4) es 4


Con el comando `del` junto con el uso de la referencia a los elementos de una lista, se pueden eliminar los elementos que se encuentren en dichos índices.

In [41]:
# Borrado de elementos a traves del comando del
print('L =', L)
del L[3]  # Borrando el elemento en el indice 3
print('L =', L)
del L[::2]  # Borrando los elementos en los indices pares
print('L =', L)

L = [1, 2, 3, 'Hola', 4, 5, 6, 7]
L = [1, 2, 3, 4, 5, 6, 7]
L = [2, 4, 6]


## Módulo `numpy`

El módulo [`numpy`](https://numpy.org/) es una biblioteca para cómputo científico que permite hacer cálculos numéricos y tener acceso a rutinas numéricas que se pueden encontrar en software especializado como por ejemplo *Matlab/Octave*. Además, dentro de este módulo se cuenta con las funciones y constantes matemáticas que encontramos en el módulo `math`.

In [49]:
#instalamos numpy así como lo hicimos con math 
!pip install numpy

     ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
     ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
     --------------------------------------- 0.1/15.8 MB 656.4 kB/s eta 0:00:24
     ---------------------------------------- 0.2/15.8 MB 1.5 MB/s eta 0:00:11
      --------------------------------------- 0.3/15.8 MB 1.9 MB/s eta 0:00:09
     - -------------------------------------- 0.5/15.8 MB 2.2 MB/s eta 0:00:07
     - -------------------------------------- 0.7/15.8 MB 2.6 MB/s eta 0:00:06
     -- ------------------------------------- 0.8/15.8 MB 2.6 MB/s eta 0:00:06
     -- ------------------------------------- 1.0/15.8 MB 2.8 MB/s eta 0:00:06
     -- ------------------------------------- 1.2/15.8 MB 2.8 MB/s eta 0:00:06
     --- ------------------------------------ 1.3/15.8 MB 2.9 MB/s eta 0:00:05
     --- ------------------------------------ 1.5/15.8 MB 2.9 MB/s eta 0:00:05
     ---- ----------------------------------- 1.6/15.8 MB 3.0 MB/


[notice] A new release of pip is available: 23.0.1 -> 24.0
[notice] To update, run: C:\Users\52556\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [50]:
# Cargando el modulo numpy con el alias np
import numpy as np

In [51]:
# Funcion coseno en numpy
np.cos(np.pi)

-1.0

In [52]:
# Funcion coseno en math
import math
math.cos(math.pi)

-1.0

### Arreglos en `numpy`

El módulo `numpy` permite generar arreglos n-dimensionales (`ndarray`, vea la  [documentación](https://numpy.org/doc/stable/reference/arrays.html) para mayor información) que se comportan de manera similar a los arreglos que se encuentran en Matlab/Octave. En particular, permite crear *vectores* (arreglos unidimensionales) de tamaño $n$
$$
    \pmb{x} = \left(\begin{array}{c} x_{1}\\x_{2}\\\ldots\\x_{n}\end{array}\right),
$$
y *matrices* (arreglos bidimensionales) de tamaño $m\times n$ ($m$ renglones y $n$ columnas)

$$
    A = \left(\begin{array}{cccc}
        a_{1,1} & a_{1,2} & \ldots & a_{1,n}\\
        a_{2,1} & a_{2,2} & \ldots & a_{2,n}\\
        \vdots  & \vdots  & \ddots & \vdots\\
        a_{m,1} & a_{m,2} & \ldots & a_{m,n}\end{array}\right).
$$

In [53]:
# Generacion de un vector a traves de una lista. Tambien se puede usar una tupla
v = np.array([1, 2, 3, 4])
print(v)
type(v)

[1 2 3 4]


numpy.ndarray

In [54]:
# Generacion de una matriz a traves de una lista bidimensional. Tambien se puede usar una tupla
M = np.array([[1, 2, 3], [4, 5, 6]])
print(M)
type(M)

[[1 2 3]
 [4 5 6]]


numpy.ndarray

**Nota**: El acceso a los elementos de los arreglos de `numpy` se puede hacer exactamente igual que para las listas y tuplas. Con ello se puede modificar sus valores mediante la referencia a un elemento o a un subconjunto de elementos usando el operador de asignación (`=`).

In [55]:
# Referencia a los elementos del vector
print('v =', v, '\n')
print('v[0] =', v[0])  # Referencia al primer elemento
print('v[1:3] =', v[1:3])  # Referencia a los elementos de la posición 1 a la 2
print('v[:] =', v[:])  # Referencia a todos los elementos

v = [1 2 3 4] 

v[0] = 1
v[1:3] = [2 3]
v[:] = [1 2 3 4]


In [56]:
# Referencia a los elementos de la matriz
print('M =\n', M, '\n')
print('M[0][0] =', M[0][0])  # Elemento en el primer renglon y primera columna M
print('M[1][:] =', M[1][:])  # Segundo renglon de M

M =
 [[1 2 3]
 [4 5 6]] 

M[0][0] = 1
M[1][:] = [4 5 6]


In [57]:
# Tipos de datos
print(type(M[0][0]))
print(type(v[0:2]))

<class 'numpy.int32'>
<class 'numpy.ndarray'>


In [58]:
# Modificando el valor del primer renglon tercera columna
M[0][2] = -1
print(M)

[[ 1  2 -1]
 [ 4  5  6]]


In [59]:
# Modificando los valores de la primera fila, y de la primera y tercera columna
M[0][:3:2] = -5
print(M)

[[-5  2 -5]
 [ 4  5  6]]


**Nota**: Sin embargo para tener acceso a submatrices como en el caso de Matlab/Octave, la clase `array` permite el manejo de los índices a través de un solo par de corchetes, y los índices correspondientes a cada dimensión se separan por comas, de forma análoga a Matlab/Octave.

In [60]:
# Intento de obtener la submatriz de todas las filas de M, y de la segunda y tercera columna de M
print('M =\n', M)
print('\nM[:][1:3] =\n', M[:][1:3])

M =
 [[-5  2 -5]
 [ 4  5  6]]

M[:][1:3] =
 [[4 5 6]]


In [61]:
# Submatriz de M de todas las filas de M, y de la segunda y tercera columna de M
print('M[:, 1:3] =\n', M[:, 1:3])

M[:, 1:3] =
 [[ 2 -5]
 [ 5  6]]


In [62]:
# Se modifican todos los valores en la submatriz con un arreglo del mismo tamaño
M[:, 1:3] = np.array([[1, 2], [3, 4]])
print('M =\n', M)

M =
 [[-5  1  2]
 [ 4  3  4]]


#### Funciones para generar arreglos y métodos sobre arreglos de `numpy`

El módulo `numpy` cuenta con un gran número de funciones que permiten generar `ndarray` con formas específicas. También cuenta con métodos para hacer manipulaciones sobre los elementos del arreglo o consultar algunos de sus atributos. Una lista completa de las funciones puede ser consultada en la siguiente [liga](https://numpy.org/doc/stable/reference/routines.html) y los métodos disponibles se puede encontrar en la siguiente [liga](https://numpy.org/doc/stable/reference/arrays.ndarray.html#array-methods).

La función `linspace` dentro de `numpy` sirve para crear vectores con elementos espaciados de manera uniforme. La sintaxis es la siguiente

```python
v = np.linspace(xi, xf, n)
```
* La variable `xi` indica el valor del primer elemento del vector.
* La variable `xf` indica el valor del último elemento del vector.
* La variable `n` indica el numero de elementos. Con la sintaxis `v = linspace(xi, xf)` la variable `n` toma el valor de 50.

Así, cada entrada del vector `v` estará dada por:
```python
v[k] = xi + kh
```
para `k` de `0` hasta `n-1` y
```python
h = (xf-xi) / (n-1)
```

In [63]:
# Ejemplo de linspace
x = np.linspace(-1, 2, 10)
print(x)

[-1.         -0.66666667 -0.33333333  0.          0.33333333  0.66666667
  1.          1.33333333  1.66666667  2.        ]


La función `arange` dentro de `numpy` también sirve para crear vectores con elementos espaciados de manera uniforme. La diferencia respecto a `linspace` es que con `arange` se especifica el espaciamiento entre elementos mientras que en `linspace` se especifica el número de elementos del vector. La sintaxis es la siguiente

```python
v = np.arange(xi, xf, h)
```
* La variable `xi` indica el valor del primer elemento del vector.
* La variable `xf` indica la cota superior valor del último elemento del vector.
* La variable `h` indica el incremento. Con la sintaxis `v = arange(xi, xf)` la variable `h` toma el valor de 1.

Así, cada entrada del vector `v` estará dada por:
```python
v[k] = xi + kh
```
para `k` $\geq$ `0` de tal manera que `xi` $\leq$ `v[k]` $<$ `xf` (`v[k]`$\in [$ `xi`, `xf` $)$).

In [64]:
# Para tener el analogo al operador : de Octave se usa arange de numpy
y = np.arange(-1,10,0.5)
print(y)

[-1.  -0.5  0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5
  6.   6.5  7.   7.5  8.   8.5  9.   9.5]


En los siguientes ejemplos se muestran algunas funciones para crear matrices con formas particulares:

* `np.ones(shape)`. Permite crear un arreglo $n$-dimensional con todas sus entradas `1.` del tamaño definido por `shape`. Para crear una matriz de tamaño $m\times n$, el argumento `shape` puede ser una lista o una tupla que contenga el número de filas y columnas si tiene dos entradas `(m, n)` o un vector con $m$ entradas si sólo contiene una `(m)` o `(m,)`.
* `np.zeros(shape)`. Permite crear un arreglo $n$-dimensional con todas sus entradas `0.` del tamaño definido por `shape`. Para crear una matriz de tamaño $m\times n$, el argumento `shape` puede ser una lista o una tupla que contenga el número de filas y columnas si tiene dos entradas `(m, n)` o un vector con $m$ entradas si sólo contiene una `(m)` o `(m,)`.
* `np.eye(m[,n])`. Permite crear una matriz de tamaño $m\times n$ donde los elementos son cero, excepto en la diagonal principal donde son 1. Si sólo se da el argumento `m` se obtendrá una matriz cuadrada de tamaño $m\times m$. El segundo argumento `n` es opcional y si se específica se tendrá una matriz rectangular de tamaño $m\times n$.

In [65]:
# Funcion ones
O = np.ones((4, 5))
print(O)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [66]:
# Funcion zeros
u = np.zeros((9))
print(u)

[0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [67]:
# Funcion eye
Q = np.eye(5)
print(Q)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Hay diversos métodos definidos para `ndarray`, estos son solo algunos ejemplos.
* `.diagonal()`. Extrae la diagonal principal.
* `.sum()`. Permite calcular la suma de todos los elementos en el arreglo. Si es un arreglo $n$-dimensional, permite hacer la suma sobre alguna dimensión específica obteniendo un arreglo $(n-1)$-dimensional.
* `.prod()`. Permite calcular el producto de todos los elementos en el arreglo. Si es un arreglo $n$-dimensional, permite hacer el producto sobre alguna dimensión específica obteniendo un arreglo $(n-1)$-dimensional.
* `.mean()`. Permite calcular la media de todos los elementos en el arreglo. Si es un arreglo $n$-dimensional, permite calcular la media sobre alguna dimensión específica obteniendo un arreglo $(n-1)$-dimensional.

In [68]:
# Metodo diagonal
O.diagonal()

array([1., 1., 1., 1.])

In [69]:
# Suma de los elementos de un vector
u.sum()

0.0

In [70]:
# Suma de los elementos de una matriz
print(O.sum())  # Suma de todos los elementos
print(O.sum(0))  # Suma por filas
print(O.sum(1))  # Suma por columnas

20.0
[4. 4. 4. 4. 4.]
[5. 5. 5. 5.]


In [71]:
# Producto de los elementos de un vector
v.prod()

24

In [72]:
# Producto de los elementos de una matriz
print(M.prod())  # Producto de todos los elementos
print(M.prod(0))  # Producto por filas
print(M.prod(1))  # Producto por columnas

-480
[-20   3   8]
[-10  48]


In [73]:
# Media de los elementos de un vector
v.mean()

2.5

In [74]:
# Media de los elementos de una matriz
print(M.mean())  # Media de todos los elementos
print(M.mean(0))  # Media por filas
print(M.mean(1))  # Media por columnas

1.5
[-0.5  2.   3. ]
[-0.66666667  3.66666667]


También se tiene acceso a ciertos atributos que proveen información sobre el arreglo. Por ejemplo,
* `.ndim`. Permite saber el número de dimensiones.
* `.shape`. Permite saber la forma de un arreglo. Si el arreglo es una matriz arroja una tupla con el número de filas y columnas y si es un vector, regresa una tupla con el número de elementos.
* `.size`. Permite saber el número de elementos que hay en el arreglo.

In [75]:
# Numero de dimensiones
print(u.ndim)  # Vector
print(O.ndim)  # Matriz

1
2


In [76]:
# Tamaño de un arreglo
print(u.shape)  # Vector
print(O.shape)  # Matriz

(9,)
(4, 5)


In [77]:
# Numero de elementos en el arreglo
print(u.size)  # Vector
print(O.size)  # Matriz

9
20


#### Operaciones y funciones sobre arreglos de `numpy`

En el caso de las operaciones, al aplicar cualquier operador aritmético estas se realizan componente a componente. Esto es, si se tienen dos arreglos de `numpy` `A` y `B` del mismo tamaño, entonces `C` $=$ `A` $\odot$ `B` para $\odot \in\{$ `+`, `-`, `/`, `*`, `%`, `//` $\}$ implica que

`C[idx1[,idx2[,idx3[...,idxN]]]]` $=$  `A[idx1[,idx2[,idx3[...,idxN]]]]` $\odot$ `B[idx1[,idx2[,idx3[...,idxN]]]]`

En particular, para vectores esto implica que:

`C[i]` $=$  `A[i]` $\odot$ `B[i]` para `i` de `0` hasta `n-1`

y para matrices

`C[i,j]` $=$  `A[i,j]` $\odot$ `B[i,j]` para `i` de `0` hasta `m-1` y `j` de `0` hasta `n-1`.

Para el caso de las potencias, tener la instrucción `A**p` implica que cada entrada del arreglo `A` será elevado a la potencia `p`, esto es `A[i]**p` para vectores y `A[i,j]**p` para matrices.

In [78]:
# Suma de vectores y multiplicacion por escalar
print(v)
print(v + 2*v)

[1 2 3 4]
[ 3  6  9 12]


In [79]:
# Multiplicacion de vectores elemento a elemento
print(v*v)

[ 1  4  9 16]


In [80]:
# Division de vectores elemento a elemento
print(v / (2*v))

[0.5 0.5 0.5 0.5]


In [81]:
# Elevar cada elemento a una potencia
print(v**3)

[ 1  8 27 64]


**Nota**: También está permitido hacer otras operaciones con escalares, lo cual tendrá el efecto de aplicar a cada entrada del arreglo esa operación con el escalar como segundo operando.

In [82]:
# Operaciones con escalares
print(v + 3)  # Suma
print(v - 10)  # Restar
print(v%2)  # Modulo
print(v/3)  # División

[4 5 6 7]
[-9 -8 -7 -6]
[1 0 1 0]
[0.33333333 0.66666667 1.         1.33333333]


Dado que la suma y resta de matrices se define como una operación elemento a elemento, con las implementaciones de esos operadores en el módulo `numpy` se tiene cubiertas esas operaciones. Sin embargo, la multiplicación de matrices para $A$ de tamaño $m\times n$ y $B$ de tamaño $n\times r$ da como resultado es una matriz $C = AB$ de tamaño $m\times r$ con entradas
$$
    C_{i,j} = \sum_{k=1}^{n} a_{i,k}b_{k,j}\quad i=1,\ldots,m,\,j=1,\ldots,r.
$$
*Nota*: Observe que el número de columnas de $A$ debe coincidir con el número de renglones de $B$.

Entonces cuando se quiere realizar la multiplicación de matrices, este debe ser realizado mediante el método *dot* o el operador *@*.

In [71]:
# Multiplicacion usual de matrices mediante dot
v.dot(O)

array([10., 10., 10., 10., 10.])

In [83]:
# Multiplicacion usual de matrices mediante la funcion dot
np.dot(v, O)

array([10., 10., 10., 10., 10.])

In [84]:
# Multiplicacion usual de matrices mediante @
v @ O

array([10., 10., 10., 10., 10.])

Otra característica es que las funciones matemáticas dentro de este módulo se pueden aplicar directamente a los arreglos, teniendo como resultado un arreglo del mismo tamaño a donde cada entrada se le aplica la función. Por ejemplo, dada la matriz `A`, entonces si se le aplica la función `np.cos()`, tendremos que si `B = np.cos(A)`, entonces `B` tiene entradas `B[i, j] = np.cos(A[i, j])`.

In [85]:
# Aplicación de funciones a vectores y matrices
print('Aplicamos coseno a un vector\n')
print(np.cos(v))
print('\nAplicamos la raiz cuadrada a una matriz\n')
print(np.sqrt(abs(M)))

Aplicamos coseno a un vector

[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]

Aplicamos la raiz cuadrada a una matriz

[[2.23606798 1.         1.41421356]
 [2.         1.73205081 2.        ]]


**Nota**: La función `abs` sirve para calcular el valor absoluto de un número. Esta función pertenece a las funciones integradas de Python, por lo que se puede aplicar a los tipos de datos numéricos. Aunque también es posible usarla con los tipos de datos del módulo `numpy`, como se muestra en el ejemplo anterior, también se puede usar la función `np.abs()` o `np.fabs()` dentro de este módulo.

Además es posible utilizar los operadores relacionales (`<`, `>`, `<=`, `>=`, `==`, `!=`) sobre los arreglos de `numpy`. En este caso se obtendran arreglos con entradas booleanas. Estas operaciones pueden ser utilizadas para crear *filtros* ya que se pueden utilizar como índices lógicos.

In [86]:
# Ejemplo de comparacion con un numero
A = np.array([[-1, 4, -5], [7, -8, 6]])
print('A =\n', A)

# Mostrando la salida de la compración
print('\nA < 0 =\n', A < 0)

# Aplicando la operacion solo a los elementos negativos.
A[A < 0] += np.abs(A).max()
print('\nA =\n', A)

A =
 [[-1  4 -5]
 [ 7 -8  6]]

A < 0 =
 [[ True False  True]
 [False  True False]]

A =
 [[7 4 3]
 [7 0 6]]


In [87]:
# Comparacion (elemento a elemento) entre arreglos del mismo tamaño
print('A =\n', A)
print('\nM =\n', M)
print('\nA > M =\n', A > M)

A =
 [[7 4 3]
 [7 0 6]]

M =
 [[-5  1  2]
 [ 4  3  4]]

A > M =
 [[ True  True  True]
 [ True False  True]]


## Ejemplos
### Ejemplo 2

Cree un vector `vec` que tenga 12 elementos de los cuales el primero sea 5, el incremento sea de 4 y el último elemento sea 49.

**Solución**: Dado que se da el incremento se puede utilizar la función `np.arange()`. Teniendo en cuenta que esta función no toma el valor final, es necesario aumentar el final en 1 para que 49 aparezca en el arreglo.

In [77]:
vec = np.arange(5, 50, 4)
print('vec:', vec)

vec: [ 5  9 13 17 21 25 29 33 37 41 45 49]


A partir de `vec` cree los siguientes vectores:

1. Un vector (`vecA`) que tenga 7 elementos. Los primeros 4 elementos deben ser los primeros 4 elementos del vector `vec`, y los últimos 3 deben ser los últimos 3 elementos del vector `vec`.

**Solución**: Aquí se puede utilizar la función `np.append()` para agregar al primer vector `vec[:4]` el segundo vector `vec[-3:]` y así construir `vecA`.

In [78]:
# Fase de inicializacion
vecA = np.append(vec[:4], vec[-3:])
print('vecA:', vecA)

vecA: [ 5  9 13 17 41 45 49]


2. Un vector (nombrelo `vecB`) que contenga todos los elementos con índice  impar de `vec`.

**Solución**: Los índices impares son 1,3,...,11. Para determinar los elementos con índice impar de `vec` esto se puede hacer a través de los slices indicando el inicio en el índice 1, dejando sin especificar el final para recorrer hasta el final y haciendo incrementos de 2.

In [79]:
# Fase de terminacion
vecB = vec[1::2]
print('vecB:', vecB)

vecB: [ 9 17 25 33 41 49]


3. Un vector (nombrelo `vecC`) que contenga todos los elementos con índice  par de `vec`.

**Solución**: Los índices impares son 0,2,...,10. Para determinar los elementos con índice impar de `vec` esto se puede hacer a través de los slices donde el inicio no se especifica (puede ser 0) para empezar desde el inicio, dejando sin especificar el final para recorrer hasta el final y haciendo incrementos de 2.

In [80]:
# Fase de terminacion
vecC = vec[::2]
print('vecC:', vecC)

vecC: [ 5 13 21 29 37 45]


### Ejemplo 3

Muestre que la suma de la serie infinita
$$
    \sqrt{12}\sum_{n=0}^{\infty}\dfrac{(-3)^{-n}}{2n+1}
$$
converge a $\pi$. Haga esto calculando las sumas:
1. $\sqrt{12}\sum_{n=0}^{10}\dfrac{(-3)^{-n}}{2n+1}$.
2. $\sqrt{12}\sum_{n=0}^{20}\dfrac{(-3)^{-n}}{2n+1}$.
3. $\sqrt{12}\sum_{n=0}^{50}\dfrac{(-3)^{-n}}{2n+1}$.

Para cada parte cree un vector $n$ en el cual el primer elemento sea 0, el incremento sea 1 y el último término sea 10, 20 ó 50. Luego, use operaciones elemento a elemento para crear un vector cuyos elementos sean $\dfrac{(-3)^{-n}}{2n+1}$. Finalmente, use el método `.sum()` para sumar los términos de la serie y multiplique el resultado por $\sqrt{12}$. Compare los valores obtenidos en los incisos 1., 2. y 3. con el valor de $\pi$ del módulo `numpy`.


**Solución**: Para calcular la suma es necesario calcular cada uno de los términos. Luego como $n$ toma valores enteros se usa `np.arange(n+1)` para generar un vector con los enteros del `0` hasta `n` que se guardan en `t_n`. Así, para calcular el término $n$-esimo de la suma sólo es necesario calcular la expresión $\dfrac{(-3)^{-n}}{2n+1}$ a cada entrada de `t_n`, que se hace usando las operaciones elemento a elemento con el vector. Una vez teniendo los términos calculados sólo se hace la suma de todas las entradas con el método `.sum()` y se multiplica por $\sqrt{12}$. Cambiando los valores de `n` por `10`, `20` y `50`, se obtienen los resultados para los incisos 1., 2. y 3., respectivamente. Conforme más términos se calculen, veremos que el error será menor.

In [81]:
# Fase de inicializacion
n = 10

# Fase de procesamiento
t_n = np.arange(n + 1)
t_n = (-3.0)**(-t_n) / (2.0*t_n + 1)

# Fase de terminacion
pi_approx = np.sqrt(12)*t_n.sum()
print(f'La aproximacion de {np.pi} con {n + 1} terminos de la suma es: {pi_approx}')
print(f'El error absoluto es: {np.fabs(pi_approx - np.pi): 2.2e}')

La aproximacion de 3.141592653589793 con 11 terminos de la suma es: 3.141593304503081
El error absoluto es:  6.51e-07


### Ejemplo 4

Considere las siguientes matrices
$$
    A = \begin{pmatrix}
        2 & 4 & -1 \\
        3 & 1 & -5 \\
        0 & 1 & 4
    \end{pmatrix}\quad
    B = \begin{pmatrix}
        -2 & 5 & 0 \\
        -3 & 2 & 7 \\
        -1 & 6 & 9
    \end{pmatrix}\quad
    C = \begin{pmatrix}
        0 & 3 & 5 \\
        2 & 1 & 0 \\
        4 & 6 & -3
    \end{pmatrix}
$$
1. ¿Se cumple que $AB = BA$?
2. ¿Se cumple que $A(BC) = (AB)C$?
3. ¿Se cumple que $(AB)^{\intercal} = B^{\intercal}A^{\intercal}$?
4. ¿Se cumple que $(A + B)^{\intercal} = A^{\intercal} + B^{\intercal}$?

**Solución**: Aquí se definen las matrices, se usa el operador `@` para realizar la multiplicación de matrices y el atributo `.T` para calcular la transpuesta de una matriz ($A^{\intercal} \equiv$`A.T`).

In [82]:
# Fase de inicializacion
A = np.array([[2, 4, -1], [3, 1, -5], [0, 1, 4]])
B = np.array([[-2, 5, 0], [-3, 2, 7], [-1, 6, 9]])
C = np.array([[0, 3, 5], [2, 1, 0], [4, 6, -3]])

# Fase de terminacion
print(f'La pregunta 1 no se cumple ya que' \
      f'\n\n AB = \n{A@B}\n\n {chr(0x2260)} \n\nBA = \n{B@A}')
print(f'\nLa pregunta 2 si se cumple ya que' \
      f'\n\n A(BC) = \n{A@(B@C)}\n\n {chr(0x003D)} \n\nA(BC) = \n{(A@B)@C}')
print(f'\nLa pregunta 3 si se cumple ya que' \
      f'\n\n (AB)^T = \n{(A@B).T}\n\n {chr(0x003D)} \n\nB^T(A^T) = \n{B.T@A.T}')
print(f'\nLa pregunta 4 si se cumple ya que' \
      f'\n\n (A+B)^T = \n{(A+B).T}\n\n {chr(0x003D)} \n\nA^T + B^T = \n{A.T+B.T}')

La pregunta 1 no se cumple ya que

 AB = 
[[-15  12  19]
 [ -4 -13 -38]
 [ -7  26  43]]

 ≠ 

BA = 
[[ 11  -3 -23]
 [  0  -3  21]
 [ 16  11   7]]

La pregunta 2 si se cumple ya que

 A(BC) = 
[[ 100   81 -132]
 [-178 -253   94]
 [ 224  263 -164]]

 = 

A(BC) = 
[[ 100   81 -132]
 [-178 -253   94]
 [ 224  263 -164]]

La pregunta 3 si se cumple ya que

 (AB)^T = 
[[-15  -4  -7]
 [ 12 -13  26]
 [ 19 -38  43]]

 = 

B^T(A^T) = 
[[-15  -4  -7]
 [ 12 -13  26]
 [ 19 -38  43]]

La pregunta 4 si se cumple ya que

 (A+B)^T = 
[[ 0  0 -1]
 [ 9  3  7]
 [-1  2 13]]

 = 

A^T + B^T = 
[[ 0  0 -1]
 [ 9  3  7]
 [-1  2 13]]
